name: Run Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Test with coverage
        run: |
          CHANGED_PKGS="${{ steps.changed-packages.outputs.list }}"
          for PKG in $CHANGED_PKGS; do
            if [[ "$PKG" != "player" ]]; then
              echo "Testing changed package with coverage: $PKG"
              pnpm --filter $PKG run test:coverage || exit 1
            fi
           done

      # TODO: add player test
      #- name: Prepare test user for player tests
      #  id: player-test-user
      #  run: |
      #    echo ${{ env.TEST_USER }} | base64 -d > test-user.json
      #    json=$(cat test-user.json)
      #    replacement=${{ secrets.PLAYER_REFRESH_TOKEN }}
      #    fixed_json="$(echo ${json/\[TOKEN\]/$replacement})"
      #    encoded_json=$(echo "$fixed_json" | base64 | tr -d '\n')
      #    echo "encoded=\"$encoded_json\"" >> $GITHUB_OUTPUT
      #  env:
      #    TEST_USER: ${{ secrets.PLAYER_TEST_USER }}

      #
      #- name: Test Player
      #  run: |
      #    pnpm --filter player run test:coverage || exit 1
      #  env:
      #    TEST_USER: ${{ steps.player-test-user.outputs.encoded }}

      - uses: codecov/codecov-action@v4
        with:
          files: packages/*/coverage/lcov.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
